### ISSUE TITLE
Kamera

### ISSUE THREAD

**Issue by rwakulszowa** [kxkaro/Skater_pygame#12]
- [ ] usunąć wszystkie dotychczasowe odniesienia do `CameraX`
- [ ] dodać klasę `Camera(x, y)`
- [ ] dodać instancję kamery jako parametr instancji `Game`
- [ ] w metodzie `Game.display_frame()` dynamicznie wyznaczyć pozycje wszystkich renderowanych elementów (na razie gracz + plansza) na podstawie pozycji kamery
  - plan jest taki, żeby oddzielić logikę gry (pozycje, kolizje itp) od logiki renderowania (display frame)
  - kamera zmienia jedynie sposób renderowania (tj. na jej podstawie wybieramy fragment planszy który chcemy wyrenderować), więc nie powinna zmieniać stanu gry (tj. pozycji gracza / przeszkód)

W praktyce znaczy to tyle, że metoda [draw_main_game](https://github.com/kxkaro/Skater_pygame/blob/master/skater/game.py#L224) będzie rysowała na podstawie `self.camera`. Funkcja `draw_sprite` może przyjmować instancję `Camera` jako argument i na jej podstawie przesuwać pozycję rysowania.

Dzięki temu oddzielimy renderowanie od stanu gry, przez co unikniemy różnych dziwnych błędów w przyszłości i całość będzie dużo łatwiej testować / debugować.

Generalna zasada jest taka, że jak coś jest ciężko testować (a renderowanie jest cholernie trudne do testowania), to niech chociaż będzie proste -> w naszym przypadku ograniczymy logikę otaczającą renderowanie do minimum.

Uprościmy też stan gry (tj. pozycja kamery na dobrą sprawę będzie odzielona od samej logiki gry), co da nam te same korzyści.

**Comment by spookydoodle** [comment]
Zerknij pan prosze i jak jest oke to zamkniemy issssszu

**Comment by rwakulszowa** [comment]
Dorzucę jeszcze 1 commit wieczorkiem i zamkniemy.
