### ISSUE TITLE
skoki na wierzcholkach obstaclow

### ISSUE THREAD

**Issue by spookydoodle** [kxkaro/Skater_pygame#15]
Witam, dalej nie dziala dobrze fall. jak skater stoi na wierzcholku i zrobi ollie w miejscu, to granica bottom jest na przemian dobrze i zle wyliczana. zalaczam screenshoty, ktore to wyjasnia.
need to resolve, warunki zle :(

![issue4_a](https://user-images.githubusercontent.com/38886624/43813668-f62e5954-9ac6-11e8-8f38-818b31b16b7d.png)
![issue4_b](https://user-images.githubusercontent.com/38886624/43813669-f667c0a4-9ac6-11e8-826b-d9b7f807f820.png)

**Comment by rwakulszowa** [comment]
Ok, najprawdopodobniej błąd w `obstacle.is_under()`.

Możemy spróbować dodać test który zreprodukuje problem a potem naprawić.

**Comment by rwakulszowa** [comment]
Faktycznie coś zepsułem w moich wczorajszych zmianach :/
