### ISSUE TITLE
Plansza jako klasa

### ISSUE THREAD

**Issue by rwakulszowa** [kxkaro/Skater_pygame#3]
Plansza, tj. zbiór przeszkód i parametrów, powinna być oddzielną klasą. Metody do sprawdzania kolizji powinny zostać przeniesione z `Game` do planszy i przyjmować parametr `player`.

**Comment by rwakulszowa** [comment]
Ewentualnie metody kolizji mogą być w klasie `Player`, ale powinny przyjmować planszę jako argument.

**Comment by rwakulszowa** [comment]
Generalnie mam na myśli coś dość prostego na początek:
```
class GameBoard:
    def __init__(self, obstacles):
        self.obstacles = obstacles
```
i jakie tam jeszcze  metody będą przydatne. Na dobrą sprawę to będzie zwykła lista przeszkód, ale chodzi o to żeby te obiekty jakoś uporządkować. W przyszłości dodamy do tego więcej metod / parametrów.

Co do metod sprawdzania kolizji(`check_collision_*`), to na razie warto będzie je przenieść nie do planszy ale do Obstacle (trochę analogicznie do metody `is_under` którą dodałem niedawno). Parę rzeczy ulegnie zmianie, tj.:
- można będzie pozbyć się wywołań `pygame.sprite.collide_rect` -> i tak robimy to sprawdzenie ręcznie, więc można to wyrzucić
- metody będą zwracać wartość `True` albo `False`, a klasa która je wywołuje (czyli w tym momencie `Game` zajmie się ustawianiem stanu na podstawie zwróconej wartości (w metodzie `check_collisions`)

Zysk z tego wszystkiego jest taki, że:
- możemy łatwo napisać testy dla logiki sprawdzającej kolizje
- rozbijamy kod na mniejsze kawałki, co jest łatwiejsze do utrzymania / czytania

**Comment by spookydoodle** [comment]
Dobra cos tam zrobilam i rozdzielilam i przygotowalam metody sprawdzania kolizji w obstacle.
Gubie sie w przeniesieniu tego wszystkiego z game do Obstacle i GameBoard.

1. Nie za bardzo wiem, w ktorym miejscu wygenerowac te obstacle, ktore teraz sa w game.create_obstacles() i jak je przekazac do gameboardu
2. Gdzie i jak zainicjalizowac GameBoard()?
3. No i chyba potem podmiana aktualnych brzydkich is_colliding na metody z Obstacle.is_leftrightunderover....

**Comment by rwakulszowa** [comment]
1 i 2: myślę, że sama logika tworzenia Obstacles i GameBoard może nadal być tam gdzie jest, tj. wewnątrz klasy Game (najlepiej w konstruktorze). Z tą różnicą, że zamiast pól `self.obstacles`, `self.all_sprites_group`, `self.all_sprites`, będziemy mieć tylko pole `self.gameboard`.
