### ISSUE TITLE
importy w state, menu, controls i game classes

### ISSUE THREAD

**Issue by spookydoodle** [kxkaro/Skater_pygame#9]
Rozdzielilam powyzsze klasy na rozne pliki, ale kazda z tych klas ma ze soba zwiazek i nie wiem jak te importy powiazac, bo tak japisales jak sie importuje w jedna i druga strone, to nie dziala. Narazie zostawilam importy: controls i game, w menu. Natomiast powrot ze stanu Controls do Menu sie wywala, bo nie wiem jak zaimportowac Menu w pliku Controls.

**Comment by rwakulszowa** [comment]
W pythonie importy działają trochę inaczej niż w C++.

Jeśli mamy moduły A i B:
- moduł A może operować na obiektach z modułu B nawet jeśli moduł B nie jest zaimportowany w A, pod warunkiem że są one przekazane przez wartość
  - tj. funkcją `A.add(x, y)` nie wymaga importu `B.whatever` żeby `add` można było wywołać na obiektach typu `B.whatever`
- import jest konieczny tylko wtedy, jeśli jeden moduł bezpośrednio używa obiektów eksportowanych przez drugi obiekt
  - tj. funkcja `A.create_whatever(): return new B.whatever()` wymaga zaimportowania `B.whatever` w module A

W naszym przypadku:
- state.py nie musi niczego importować, bo niczego nie używa
- generalnie cykliczne zależności (i dużo importów ogółem) to raczej zły znak i dobrze jest posprzątać kod w taki sposób, żeby struktura była jak najprostsza -> zazwyczaj rozwiązaniem jest przekazywanie zależnych obiektów przez wartość, zamiast importowania klas - [wstrzykiwanie zależności](https://en.wikipedia.org/wiki/Dependency_injection) (postaram się tym zająć w tym tygodniu)
- generalnie preferowane jest sprecyzowane importowanie obiektów
  - tj. zamiast `import * from A` preferowane jest `import A1, A2, A3 from A`
  - łatwiej się to czyta, łatwiej też znaleźć problemy z importami w ten sposób

**Comment by rwakulszowa** [comment]
Akurat w tym przypadku (Controls <-> Menu) możliwe było rozwiązanie przez dodanie modułu pośredniego (Destinations).

W ten sposób każdy stan importuje tylko prosty moduł Destinations, który umożliwia mapowanie między modułami, jednocześnie nie mając żadnych zależności. Wadą tego rozwiązania jest konieczność dopisania dodatkowej logiki (w pliku main), ale i tak byśmy tego potrzebowali w przyszłości.
